version: '3'
services:
  nuxt:
    container_name: nuxt-app-container
    image: nuxt-app-image
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    tty: true
    working_dir: /app
    command: npm run dev
